In [1]:
import pandas as pd
import seaborn as sns

In [50]:
data = pd.read_csv("ml_challenge_dataset.csv")

print("first 4 rows of data:")
data.head()

first 4 rows of data:

,unique_id,Painting,"On a scale of 1–10, how intense is the emotion conveyed by the artwork?",Describe how this painting makes you feel.,This art piece makes me feel sombre.,This art piece makes me feel content.,This art piece makes me feel calm.,This art piece makes me feel uneasy.,How many prominent colours do you notice in this painting?,How many objects caught your eye in the painting?,How much (in Canadian dollars) would you be willing to pay for this painting?,"If you could purchase this painting, which room would you put that painting in?","If you could view this art in person, who would you want to view it with?",What season does this art piece remind you of?,"If this painting was a food, what would be?",Imagine a soundtrack for this painting. Describe that soundtrack without naming any objects in the painting.
0,1,The Persistence of Memory,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,The Persistence of Memory,5.0,"The clocks are burnt on a hot desert, it embod...",4 - Agree,3 - Neutral/Unsure,2 - Disagree,1 - Strongly disagree,2.0,4.0,0,Bathroom,By yourself,Fall,Fries,A country song that contrasts nostalgia for th...
2,3,The Persistence of Memory,7.0,This painting makes me feel dread. The clock r...,4 - Agree,1 - Strongly disagree,1 - Strongly disagree,4 - Agree,4.0,3.0,$5,"Bathroom,Dining room","Coworkers/Classmates,By yourself",Fall,Sardines,A melancholy instrumental with a monotone voic...
3,4,The Persistence of Memory,7.0,Deflated,4 - Agree,1 - Strongly disagree,2 - Disagree,4 - Agree,10.0,7.0,a,"Bedroom,Bathroom",Coworkers/Classmates,Winter,a,q
4,5,The Persistence of Memory,7.0,The painting gives me a sense of calmness and ...,3 - Neutral/Unsure,4 - Agree,5 - Strongly agree,3 - Neutral/Unsure,4.0,6.0,300 dollars.,Living room,Friends,"Spring,Summer",Churros.,Radiohead's album in rainbows.

In [51]:
print("statistical summary for numerical features:")
data.describe()

statistical summary for numerical features:

,unique_id,"On a scale of 1–10, how intense is the emotion conveyed by the artwork?",How many prominent colours do you notice in this painting?,How many objects caught your eye in the painting?
count,1686.000000,1621.000000,1612.000000,1612.000000
mean,281.500000,6.321900,3.878412,3.977047
std,162.283303,2.195637,3.495867,3.824206
min,1.000000,0.000000,0.000000,0.000000
25%,141.000000,5.000000,3.000000,2.000000
50%,281.500000,7.000000,3.000000,3.000000
75%,422.000000,8.000000,5.000000,5.000000
max,562.000000,10.000000,100.000000,100.000000

We have 14 Questions:

$\bullet$ **Q1**: On a scale of 1–10, how intense is the emotion conveyed by the artwork? <br>
$\bullet$ **Q2**: Describe how this painting makes you feel.<br>
$\bullet$ **Q3**: This art piece makes me feel sombre.<br>
$\bullet$ **Q4**: This art piece makes me feel content.<br>
$\bullet$ **Q5**: This art piece makes me feel calm.<br>
$\bullet$ **Q6**: This art piece makes me feel uneasy.<br>
$\bullet$ **Q7**: How many prominent colors do you notice in this painting?<br>
$\bullet$ **Q8**: How many objects caught your eye in the painting?<br>
$\bullet$ **Q9**: How much (in Canadian dollars) would you be willing to pay for this painting?<br>
$\bullet$ **Q10**: If you could purchase this painting, which room would you put that painting in?<br>
$\bullet$ **Q11**: If you could view this art in person, who would you want to view it with?<br>
$\bullet$ **Q12**: What season does this art piece remind you of?<br>
$\bullet$ **Q13**: If this painting was a food, what would be?<br>
$\bullet$ **Q14**: Imagine a soundtrack for this painting. Describe that soundtrack without naming any objects in the painting.

In [52]:
# Changing the name of the columns from the their respective questions to their question number:
data = data.rename(columns={
    "On a scale of 1–10, how intense is the emotion conveyed by the artwork?": "Q1",
    "Describe how this painting makes you feel.": "Q2",
    "This art piece makes me feel sombre.": "Q3",
    "This art piece makes me feel content.": "Q4",
    "This art piece makes me feel calm.": "Q5",
    "This art piece makes me feel uneasy.": "Q6",
    "How many prominent colours do you notice in this painting?": "Q7",
    "How many objects caught your eye in the painting?": "Q8",
    "How much (in Canadian dollars) would you be willing to pay for this painting?": "Q9",
    "If you could purchase this painting, which room would you put that painting in?": "Q10",
    "If you could view this art in person, who would you want to view it with?": "Q11", 
    "What season does this art piece remind you of?": "Q12",
    "If this painting was a food, what would be?": "Q13",
    "Imagine a soundtrack for this painting. Describe that soundtrack without naming any objects in the painting.": "Q14"
})

data.head()

,unique_id,Painting,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14
0,1,The Persistence of Memory,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,The Persistence of Memory,5.0,"The clocks are burnt on a hot desert, it embod...",4 - Agree,3 - Neutral/Unsure,2 - Disagree,1 - Strongly disagree,2.0,4.0,0,Bathroom,By yourself,Fall,Fries,A country song that contrasts nostalgia for th...
2,3,The Persistence of Memory,7.0,This painting makes me feel dread. The clock r...,4 - Agree,1 - Strongly disagree,1 - Strongly disagree,4 - Agree,4.0,3.0,$5,"Bathroom,Dining room","Coworkers/Classmates,By yourself",Fall,Sardines,A melancholy instrumental with a monotone voic...
3,4,The Persistence of Memory,7.0,Deflated,4 - Agree,1 - Strongly disagree,2 - Disagree,4 - Agree,10.0,7.0,a,"Bedroom,Bathroom",Coworkers/Classmates,Winter,a,q
4,5,The Persistence of Memory,7.0,The painting gives me a sense of calmness and ...,3 - Neutral/Unsure,4 - Agree,5 - Strongly agree,3 - Neutral/Unsure,4.0,6.0,300 dollars.,Living room,Friends,"Spring,Summer",Churros.,Radiohead's album in rainbows.

We want to make this data as Numeric as possible, right now we only have 3 questions that is numeric. We can see that Q3, Q4, Q5, Q6, Q10, Q11, Q12 have responses that are categorical, so we can create indicator features for them:

**Making Q3, Q4, Q5, Q6 Numeric**

Technically, these questions are already numeric, they just have their numeric values paired with text we don't need, so we can just remove them for these questions:

In [53]:
# Creating new columns that just contain the numerical values:
data["Q3"] = (
    data["Q3"]
    .str.split(" - ")
    .str[0]
    .astype(float)
)

data["Q4"] = (
    data["Q4"]
    .str.split(" - ")
    .str[0]
    .astype(float)
)

data["Q5"] = (
    data["Q5"]
    .str.split(" - ")
    .str[0]
    .astype(float)
)

data["Q6"] = (
    data["Q6"]
    .str.split(" - ")
    .str[0]
    .astype(float)
)

**Making Q9 Numeric**

It seems that Q9 is basically a numeric question, but is made to be text, we are not interested in the text, so we can remove them:

In [54]:
# Converting responses to numeric only.
data["Q9"] = data["Q9"].str.extract(r'(\d+\.?\d*)').astype(float)

**Making Q10, Q11, Q12 Numeric**

These are questions that have categorical responses, so we can create indicator features for them.

In [55]:
# Creating indicator features for Q: If you could purchase this painting, which room would you put that painting in?
data["10a"] = data["Q10"].apply(lambda x: 1 if "Bedroom" in str(x) else 0)
data["10b"] = data["Q10"].apply(lambda x: 1 if "Bathroom" in str(x) else 0)
data["10c"] = data["Q10"].apply(lambda x: 1 if "Office" in str(x) else 0)
data["10d"] = data["Q10"].apply(lambda x: 1 if "Living room" in str(x) else 0)
data["10e"] = data["Q10"].apply(lambda x: 1 if "Dining room" in str(x) else 0)

# Creating indicator features for Q: If you could view this art in person, who would you want to view it with?
data["11a"] = data["Q11"].apply(lambda x: 1 if "Friends" in str(x) else 0)
data["11b"] = data["Q11"].apply(lambda x: 1 if "Family members" in str(x) else 0)
data["11c"] = data["Q11"].apply(lambda x: 1 if "Coworkers/Classmates" in str(x) else 0)
data["11d"] = data["Q11"].apply(lambda x: 1 if "Strangers" in str(x) else 0)
data["11e"] = data["Q11"].apply(lambda x: 1 if "By yourself" in str(x) else 0)

# Creating indicator features for Q: What season does this art piece remind you of?
data["12a"] = data["Q12"].apply(lambda x: 1 if "Spring" in str(x) else 0)
data["12b"] = data["Q12"].apply(lambda x: 1 if "Summer" in str(x) else 0)
data["12c"] = data["Q12"].apply(lambda x: 1 if "Fall" in str(x) else 0)
data["12d"] = data["Q12"].apply(lambda x: 1 if "Winter" in str(x) else 0)

# We can drop the original columns:
data.drop("Q10", axis=1, inplace=True)
data.drop("Q11", axis=1, inplace=True)
data.drop("Q12", axis=1, inplace=True)

Notice that we have some NaN entries. We should remove these entries:

In [56]:
data = data.dropna()

**Making the Output Numeric**

We have three paintings that a new input can be classified as: "The Persistence of Memory", "The Water Lily Pond", "The Starry Night". We can map these as 1,2,3:

In [57]:
# Create new mappings
painting_mapping = {"The Persistence of Memory": 1, "The Water Lily Pond": 2, "The Starry Night": 3}

# Map paintings to numerical values.
data["Painting"] = data["Painting"].map(painting_mapping)

In [58]:
data.head()

,unique_id,Painting,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,...,10e,11a,11b,11c,11d,11e,12a,12b,12c,12d
1,2,1,5.0,"The clocks are burnt on a hot desert, it embod...",4.0,3.0,2.0,1.0,2.0,4.0,...,0,0,0,0,0,1,0,0,1,0
2,3,1,7.0,This painting makes me feel dread. The clock r...,4.0,1.0,1.0,4.0,4.0,3.0,...,1,0,0,1,0,1,0,0,1,0
4,5,1,7.0,The painting gives me a sense of calmness and ...,3.0,4.0,5.0,3.0,4.0,6.0,...,0,1,0,0,0,0,1,1,0,0
5,6,1,7.0,This painting makes me feel a bit confused and...,4.0,2.0,1.0,5.0,5.0,6.0,...,0,1,1,0,0,1,0,1,1,0
6,7,1,8.0,It has a sorrow feeling and clock is melting f...,4.0,2.0,2.0,4.0,3.0,3.0,...,0,0,0,0,0,1,0,0,0,1