In [ ]:
import pandas as pd
import seaborn as sns

In [38]:
data = pd.read_csv("ml_challenge_dataset.csv")

print("first 4 rows of data:")
data.head()

first 4 rows of data:

,unique_id,Painting,"On a scale of 1–10, how intense is the emotion conveyed by the artwork?",Describe how this painting makes you feel.,This art piece makes me feel sombre.,This art piece makes me feel content.,This art piece makes me feel calm.,This art piece makes me feel uneasy.,How many prominent colours do you notice in this painting?,How many objects caught your eye in the painting?,How much (in Canadian dollars) would you be willing to pay for this painting?,"If you could purchase this painting, which room would you put that painting in?","If you could view this art in person, who would you want to view it with?",What season does this art piece remind you of?,"If this painting was a food, what would be?",Imagine a soundtrack for this painting. Describe that soundtrack without naming any objects in the painting.
0,1,The Persistence of Memory,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,The Persistence of Memory,5.0,"The clocks are burnt on a hot desert, it embod...",4 - Agree,3 - Neutral/Unsure,2 - Disagree,1 - Strongly disagree,2.0,4.0,0,Bathroom,By yourself,Fall,Fries,A country song that contrasts nostalgia for th...
2,3,The Persistence of Memory,7.0,This painting makes me feel dread. The clock r...,4 - Agree,1 - Strongly disagree,1 - Strongly disagree,4 - Agree,4.0,3.0,$5,"Bathroom,Dining room","Coworkers/Classmates,By yourself",Fall,Sardines,A melancholy instrumental with a monotone voic...
3,4,The Persistence of Memory,7.0,Deflated,4 - Agree,1 - Strongly disagree,2 - Disagree,4 - Agree,10.0,7.0,a,"Bedroom,Bathroom",Coworkers/Classmates,Winter,a,q
4,5,The Persistence of Memory,7.0,The painting gives me a sense of calmness and ...,3 - Neutral/Unsure,4 - Agree,5 - Strongly agree,3 - Neutral/Unsure,4.0,6.0,300 dollars.,Living room,Friends,"Spring,Summer",Churros.,Radiohead's album in rainbows.

In [39]:
data.shape

(1686, 16)

Notice how someone didn't answer all of the questions. We should remove any responses that have NaN entries:

In [40]:
data = data.dropna()
data.head()

,unique_id,Painting,"On a scale of 1–10, how intense is the emotion conveyed by the artwork?",Describe how this painting makes you feel.,This art piece makes me feel sombre.,This art piece makes me feel content.,This art piece makes me feel calm.,This art piece makes me feel uneasy.,How many prominent colours do you notice in this painting?,How many objects caught your eye in the painting?,How much (in Canadian dollars) would you be willing to pay for this painting?,"If you could purchase this painting, which room would you put that painting in?","If you could view this art in person, who would you want to view it with?",What season does this art piece remind you of?,"If this painting was a food, what would be?",Imagine a soundtrack for this painting. Describe that soundtrack without naming any objects in the painting.
1,2,The Persistence of Memory,5.0,"The clocks are burnt on a hot desert, it embod...",4 - Agree,3 - Neutral/Unsure,2 - Disagree,1 - Strongly disagree,2.0,4.0,0,Bathroom,By yourself,Fall,Fries,A country song that contrasts nostalgia for th...
2,3,The Persistence of Memory,7.0,This painting makes me feel dread. The clock r...,4 - Agree,1 - Strongly disagree,1 - Strongly disagree,4 - Agree,4.0,3.0,$5,"Bathroom,Dining room","Coworkers/Classmates,By yourself",Fall,Sardines,A melancholy instrumental with a monotone voic...
3,4,The Persistence of Memory,7.0,Deflated,4 - Agree,1 - Strongly disagree,2 - Disagree,4 - Agree,10.0,7.0,a,"Bedroom,Bathroom",Coworkers/Classmates,Winter,a,q
4,5,The Persistence of Memory,7.0,The painting gives me a sense of calmness and ...,3 - Neutral/Unsure,4 - Agree,5 - Strongly agree,3 - Neutral/Unsure,4.0,6.0,300 dollars.,Living room,Friends,"Spring,Summer",Churros.,Radiohead's album in rainbows.
5,6,The Persistence of Memory,7.0,This painting makes me feel a bit confused and...,4 - Agree,2 - Disagree,1 - Strongly disagree,5 - Strongly agree,5.0,6.0,90000,"Office,Living room","Friends,Family members,By yourself","Summer,Fall",Shepherd's pie,"The soundtrack should sound heavy, sombre, and..."

In [41]:
data.shape

(1592, 16)

We don't lose that many entries, we still have enough data.

In [42]:
print("statistical summary for numerical features:")
data.describe()

statistical summary for numerical features:

,unique_id,"On a scale of 1–10, how intense is the emotion conveyed by the artwork?",How many prominent colours do you notice in this painting?,How many objects caught your eye in the painting?
count,1592.000000,1592.000000,1592.000000,1592.000000
mean,284.217965,6.321482,3.863065,3.962940
std,165.276177,2.195242,3.501831,3.822657
min,2.000000,0.000000,0.000000,0.000000
25%,136.750000,5.000000,3.000000,2.000000
50%,294.000000,7.000000,3.000000,3.000000
75%,429.250000,8.000000,4.000000,5.000000
max,562.000000,10.000000,100.000000,100.000000

We want to make this data as Numeric as possible, right now we only have 3 questions that is numeric. We can see that Q3, Q4, Q5, Q6, Q10, Q11, Q12 have responses that are categorical, so we can create indicator features for them:

**Making Q3, Q4, Q5, Q6 Numeric**

Technically, these questions are already numeric, they just have their numeric values paired with text we don't need, so we can just remove them for these questions:

In [44]:
# Creating new columns that just contain the numerical values:
data["This art piece makes me feel sombre."] = (
    data["This art piece makes me feel sombre."]
    .str.split(" - ")
    .str[0]
    .astype(float)
)

data["This art piece makes me feel content."] = (
    data["This art piece makes me feel content."]
    .str.split(" - ")
    .str[0]
    .astype(float)
)

data["This art piece makes me feel calm."] = (
    data["This art piece makes me feel calm."]
    .str.split(" - ")
    .str[0]
    .astype(float)
)

data["This art piece makes me feel uneasy."] = (
    data["This art piece makes me feel uneasy."]
    .str.split(" - ")
    .str[0]
    .astype(float)
)

In [45]:
data.head()

,unique_id,Painting,"On a scale of 1–10, how intense is the emotion conveyed by the artwork?",Describe how this painting makes you feel.,This art piece makes me feel sombre.,This art piece makes me feel content.,This art piece makes me feel calm.,This art piece makes me feel uneasy.,How many prominent colours do you notice in this painting?,How many objects caught your eye in the painting?,How much (in Canadian dollars) would you be willing to pay for this painting?,"If you could purchase this painting, which room would you put that painting in?","If you could view this art in person, who would you want to view it with?",What season does this art piece remind you of?,"If this painting was a food, what would be?",Imagine a soundtrack for this painting. Describe that soundtrack without naming any objects in the painting.
1,2,The Persistence of Memory,5.0,"The clocks are burnt on a hot desert, it embod...",4.0,3.0,2.0,1.0,2.0,4.0,0,Bathroom,By yourself,Fall,Fries,A country song that contrasts nostalgia for th...
2,3,The Persistence of Memory,7.0,This painting makes me feel dread. The clock r...,4.0,1.0,1.0,4.0,4.0,3.0,$5,"Bathroom,Dining room","Coworkers/Classmates,By yourself",Fall,Sardines,A melancholy instrumental with a monotone voic...
3,4,The Persistence of Memory,7.0,Deflated,4.0,1.0,2.0,4.0,10.0,7.0,a,"Bedroom,Bathroom",Coworkers/Classmates,Winter,a,q
4,5,The Persistence of Memory,7.0,The painting gives me a sense of calmness and ...,3.0,4.0,5.0,3.0,4.0,6.0,300 dollars.,Living room,Friends,"Spring,Summer",Churros.,Radiohead's album in rainbows.
5,6,The Persistence of Memory,7.0,This painting makes me feel a bit confused and...,4.0,2.0,1.0,5.0,5.0,6.0,90000,"Office,Living room","Friends,Family members,By yourself","Summer,Fall",Shepherd's pie,"The soundtrack should sound heavy, sombre, and..."

**Making Q9 Numeric**

It seems that Q9 is basically a numeric question, but is made to be text, we are not interested in the text, so we can remove them:

In [ ]:
# Converting responses to numeric only.
data["How much (in Canadian dollars) would you be willing to pay for this painting?"] = data["How much (in Canadian dollars) would you be willing to pay for this painting?"].str.extract(r'(\d+\.?\d*)').astype(float)

# Drop NaN responses that might occur.
data=data.dropna()

data.head()

In [ ]:
data.shape

We only lost a few more entries, we still have more than plenty.

**Making Q10, Q11, Q12 Numeric**

These are questions that have categorical responses, so we can create indicator features for them.

In [49]:
# Creating indicator features for Q: If you could purchase this painting, which room would you put that painting in?
data["10a"] = data["If you could purchase this painting, which room would you put that painting in?"].apply(lambda x: 1 if "Bedroom" in str(x) else 0)
data["10b"] = data["If you could purchase this painting, which room would you put that painting in?"].apply(lambda x: 1 if "Bathroom" in str(x) else 0)
data["10c"] = data["If you could purchase this painting, which room would you put that painting in?"].apply(lambda x: 1 if "Office" in str(x) else 0)
data["10d"] = data["If you could purchase this painting, which room would you put that painting in?"].apply(lambda x: 1 if "Living room" in str(x) else 0)
data["10e"] = data["If you could purchase this painting, which room would you put that painting in?"].apply(lambda x: 1 if "Dining room" in str(x) else 0)

# Creating indicator features for Q: If you could view this art in person, who would you want to view it with?
data["11a"] = data["If you could view this art in person, who would you want to view it with?"].apply(lambda x: 1 if "Friends" in str(x) else 0)
data["11b"] = data["If you could view this art in person, who would you want to view it with?"].apply(lambda x: 1 if "Family members" in str(x) else 0)
data["11c"] = data["If you could view this art in person, who would you want to view it with?"].apply(lambda x: 1 if "Coworkers/Classmates" in str(x) else 0)
data["11d"] = data["If you could view this art in person, who would you want to view it with?"].apply(lambda x: 1 if "Strangers" in str(x) else 0)
data["11e"] = data["If you could view this art in person, who would you want to view it with?"].apply(lambda x: 1 if "By yourself" in str(x) else 0)

# Creating indicator features for Q: What season does this art piece remind you of?
data["12a"] = data["What season does this art piece remind you of?"].apply(lambda x: 1 if "Spring" in str(x) else 0)
data["12b"] = data["What season does this art piece remind you of?"].apply(lambda x: 1 if "Summer" in str(x) else 0)
data["12c"] = data["What season does this art piece remind you of?"].apply(lambda x: 1 if "Fall" in str(x) else 0)
data["12d"] = data["What season does this art piece remind you of?"].apply(lambda x: 1 if "Winter" in str(x) else 0)

# We can drop the original columns:
data.drop("If you could purchase this painting, which room would you put that painting in?", axis=1, inplace=True)
data.drop("If you could view this art in person, who would you want to view it with?", axis=1, inplace=True)
data.drop("What season does this art piece remind you of?", axis=1, inplace=True)

data.head()

,unique_id,Painting,"On a scale of 1–10, how intense is the emotion conveyed by the artwork?",Describe how this painting makes you feel.,This art piece makes me feel sombre.,This art piece makes me feel content.,This art piece makes me feel calm.,This art piece makes me feel uneasy.,How many prominent colours do you notice in this painting?,How many objects caught your eye in the painting?,...,10e,11a,11b,11c,11d,11e,12a,12b,12c,12d
1,2,The Persistence of Memory,5.0,"The clocks are burnt on a hot desert, it embod...",4.0,3.0,2.0,1.0,2.0,4.0,...,0,0,0,0,0,1,0,0,1,0
2,3,The Persistence of Memory,7.0,This painting makes me feel dread. The clock r...,4.0,1.0,1.0,4.0,4.0,3.0,...,1,0,0,1,0,1,0,0,1,0
3,4,The Persistence of Memory,7.0,Deflated,4.0,1.0,2.0,4.0,10.0,7.0,...,0,0,0,1,0,0,0,0,0,1
4,5,The Persistence of Memory,7.0,The painting gives me a sense of calmness and ...,3.0,4.0,5.0,3.0,4.0,6.0,...,0,1,0,0,0,0,1,1,0,0
5,6,The Persistence of Memory,7.0,This painting makes me feel a bit confused and...,4.0,2.0,1.0,5.0,5.0,6.0,...,0,1,1,0,0,1,0,1,1,0