In [2]:
import pandas as pd
import seaborn as sns

In [326]:
data = pd.read_csv("ml_challenge_dataset.csv")

print("first 4 rows of data:")
data.head()

first 4 rows of data:

,unique_id,Painting,"On a scale of 1–10, how intense is the emotion conveyed by the artwork?",Describe how this painting makes you feel.,This art piece makes me feel sombre.,This art piece makes me feel content.,This art piece makes me feel calm.,This art piece makes me feel uneasy.,How many prominent colours do you notice in this painting?,How many objects caught your eye in the painting?,How much (in Canadian dollars) would you be willing to pay for this painting?,"If you could purchase this painting, which room would you put that painting in?","If you could view this art in person, who would you want to view it with?",What season does this art piece remind you of?,"If this painting was a food, what would be?",Imagine a soundtrack for this painting. Describe that soundtrack without naming any objects in the painting.
0,1,The Persistence of Memory,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,The Persistence of Memory,5.0,"The clocks are burnt on a hot desert, it embod...",4 - Agree,3 - Neutral/Unsure,2 - Disagree,1 - Strongly disagree,2.0,4.0,0,Bathroom,By yourself,Fall,Fries,A country song that contrasts nostalgia for th...
2,3,The Persistence of Memory,7.0,This painting makes me feel dread. The clock r...,4 - Agree,1 - Strongly disagree,1 - Strongly disagree,4 - Agree,4.0,3.0,$5,"Bathroom,Dining room","Coworkers/Classmates,By yourself",Fall,Sardines,A melancholy instrumental with a monotone voic...
3,4,The Persistence of Memory,7.0,Deflated,4 - Agree,1 - Strongly disagree,2 - Disagree,4 - Agree,10.0,7.0,a,"Bedroom,Bathroom",Coworkers/Classmates,Winter,a,q
4,5,The Persistence of Memory,7.0,The painting gives me a sense of calmness and ...,3 - Neutral/Unsure,4 - Agree,5 - Strongly agree,3 - Neutral/Unsure,4.0,6.0,300 dollars.,Living room,Friends,"Spring,Summer",Churros.,Radiohead's album in rainbows.

In [327]:
print("statistical summary for numerical features:")
data.describe()

statistical summary for numerical features:

,unique_id,"On a scale of 1–10, how intense is the emotion conveyed by the artwork?",How many prominent colours do you notice in this painting?,How many objects caught your eye in the painting?
count,1686.000000,1621.000000,1612.000000,1612.000000
mean,281.500000,6.321900,3.878412,3.977047
std,162.283303,2.195637,3.495867,3.824206
min,1.000000,0.000000,0.000000,0.000000
25%,141.000000,5.000000,3.000000,2.000000
50%,281.500000,7.000000,3.000000,3.000000
75%,422.000000,8.000000,5.000000,5.000000
max,562.000000,10.000000,100.000000,100.000000

We have 14 Questions:

$\bullet$ **Q1**: On a scale of 1–10, how intense is the emotion conveyed by the artwork? <br>
$\bullet$ **Q2**: Describe how this painting makes you feel.<br>
$\bullet$ **Q3**: This art piece makes me feel sombre.<br>
$\bullet$ **Q4**: This art piece makes me feel content.<br>
$\bullet$ **Q5**: This art piece makes me feel calm.<br>
$\bullet$ **Q6**: This art piece makes me feel uneasy.<br>
$\bullet$ **Q7**: How many prominent colors do you notice in this painting?<br>
$\bullet$ **Q8**: How many objects caught your eye in the painting?<br>
$\bullet$ **Q9**: How much (in Canadian dollars) would you be willing to pay for this painting?<br>
$\bullet$ **Q10**: If you could purchase this painting, which room would you put that painting in?<br>
$\bullet$ **Q11**: If you could view this art in person, who would you want to view it with?<br>
$\bullet$ **Q12**: What season does this art piece remind you of?<br>
$\bullet$ **Q13**: If this painting was a food, what would be?<br>
$\bullet$ **Q14**: Imagine a soundtrack for this painting. Describe that soundtrack without naming any objects in the painting.

In [328]:
# Changing the name of the columns from the their respective questions to their question number:
data = data.rename(columns={
    "On a scale of 1–10, how intense is the emotion conveyed by the artwork?": "Q1",
    "Describe how this painting makes you feel.": "Q2",
    "This art piece makes me feel sombre.": "Q3",
    "This art piece makes me feel content.": "Q4",
    "This art piece makes me feel calm.": "Q5",
    "This art piece makes me feel uneasy.": "Q6",
    "How many prominent colours do you notice in this painting?": "Q7",
    "How many objects caught your eye in the painting?": "Q8",
    "How much (in Canadian dollars) would you be willing to pay for this painting?": "Q9",
    "If you could purchase this painting, which room would you put that painting in?": "Q10",
    "If you could view this art in person, who would you want to view it with?": "Q11", 
    "What season does this art piece remind you of?": "Q12",
    "If this painting was a food, what would be?": "Q13",
    "Imagine a soundtrack for this painting. Describe that soundtrack without naming any objects in the painting.": "Q14"
})

data.head()

,unique_id,Painting,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14
0,1,The Persistence of Memory,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,The Persistence of Memory,5.0,"The clocks are burnt on a hot desert, it embod...",4 - Agree,3 - Neutral/Unsure,2 - Disagree,1 - Strongly disagree,2.0,4.0,0,Bathroom,By yourself,Fall,Fries,A country song that contrasts nostalgia for th...
2,3,The Persistence of Memory,7.0,This painting makes me feel dread. The clock r...,4 - Agree,1 - Strongly disagree,1 - Strongly disagree,4 - Agree,4.0,3.0,$5,"Bathroom,Dining room","Coworkers/Classmates,By yourself",Fall,Sardines,A melancholy instrumental with a monotone voic...
3,4,The Persistence of Memory,7.0,Deflated,4 - Agree,1 - Strongly disagree,2 - Disagree,4 - Agree,10.0,7.0,a,"Bedroom,Bathroom",Coworkers/Classmates,Winter,a,q
4,5,The Persistence of Memory,7.0,The painting gives me a sense of calmness and ...,3 - Neutral/Unsure,4 - Agree,5 - Strongly agree,3 - Neutral/Unsure,4.0,6.0,300 dollars.,Living room,Friends,"Spring,Summer",Churros.,Radiohead's album in rainbows.

We want to make this data as Numeric as possible, right now we only have 3 questions that is numeric. We can see that Q3, Q4, Q5, Q6, Q10, Q11, Q12 have responses that are categorical, so we can create indicator features for them:

**Making Q3, Q4, Q5, Q6 Numeric**

Technically, these questions are already numeric, they just have their numeric values paired with text we don't need, so we can just remove them for these questions:

In [329]:
# Creating new columns that just contain the numerical values:
data["Q3"] = (
    data["Q3"]
    .str.split(" - ")
    .str[0]
    .astype(float)
)

data["Q4"] = (
    data["Q4"]
    .str.split(" - ")
    .str[0]
    .astype(float)
)

data["Q5"] = (
    data["Q5"]
    .str.split(" - ")
    .str[0]
    .astype(float)
)

data["Q6"] = (
    data["Q6"]
    .str.split(" - ")
    .str[0]
    .astype(float)
)

**Making Q9 Numeric**

It seems that Q9 is basically a numeric question, but is made to be text, we are not interested in the text, so we can remove them:

In [330]:
# Converting responses to numeric only.
data["Q9"] = data["Q9"].str.extract(r'(\d+\.?\d*)').astype(float)

**Making Q10, Q11, Q12 Numeric**

These are questions that have categorical responses, so we can create indicator features for them.

In [331]:
# Creating indicator features for Q: If you could purchase this painting, which room would you put that painting in?
data["10a"] = data["Q10"].apply(lambda x: 1 if "Bedroom" in str(x) else 0)
data["10b"] = data["Q10"].apply(lambda x: 1 if "Bathroom" in str(x) else 0)
data["10c"] = data["Q10"].apply(lambda x: 1 if "Office" in str(x) else 0)
data["10d"] = data["Q10"].apply(lambda x: 1 if "Living room" in str(x) else 0)
data["10e"] = data["Q10"].apply(lambda x: 1 if "Dining room" in str(x) else 0)

# Creating indicator features for Q: If you could view this art in person, who would you want to view it with?
data["11a"] = data["Q11"].apply(lambda x: 1 if "Friends" in str(x) else 0)
data["11b"] = data["Q11"].apply(lambda x: 1 if "Family members" in str(x) else 0)
data["11c"] = data["Q11"].apply(lambda x: 1 if "Coworkers/Classmates" in str(x) else 0)
data["11d"] = data["Q11"].apply(lambda x: 1 if "Strangers" in str(x) else 0)
data["11e"] = data["Q11"].apply(lambda x: 1 if "By yourself" in str(x) else 0)

# Creating indicator features for Q: What season does this art piece remind you of?
data["12a"] = data["Q12"].apply(lambda x: 1 if "Spring" in str(x) else 0)
data["12b"] = data["Q12"].apply(lambda x: 1 if "Summer" in str(x) else 0)
data["12c"] = data["Q12"].apply(lambda x: 1 if "Fall" in str(x) else 0)
data["12d"] = data["Q12"].apply(lambda x: 1 if "Winter" in str(x) else 0)

# We can drop the original columns:
data.drop("Q10", axis=1, inplace=True)
data.drop("Q11", axis=1, inplace=True)
data.drop("Q12", axis=1, inplace=True)

# We dont want any entries where the respondent did not answer the question:
cols_10 = ["10a", "10b", "10c", "10d", "10e"]
cols_11 = ["11a", "11b", "11c", "11d", "11e"]
cols_12 = ["12a", "12b", "12c", "12d"]

data = data[data[cols_10].sum(axis=1) > 0]
data = data[data[cols_11].sum(axis=1) > 0]
data = data[data[cols_12].sum(axis=1) > 0]

Notice that we have some NaN entries. We should remove these entries:

In [332]:
data = data.dropna()

Making **Q13** Numeric

Q13 is different, it is completely text based, but because most responses will be a one word answer, we can't do a bag of words approach. Instead we should try to see which foods show up the most, and make this a categorical question, from which we can create
indicator features.

In [333]:
# Start by seeing how many responses of food we got.
food_counts = data["Q13"].value_counts().to_dict()
print(food_counts)

{'Salad': 43, 'salad': 25, 'Ice cream': 24, 'Pizza': 21, 'ice cream': 19, 'pizza': 15, 'Soup': 14, 'bread': 11, 'cake': 10, 'blueberry': 9, 'Cheese': 8, 'watermelon': 8, 'Pasta': 8, 'soup': 8, 'Steak': 8, 'Spaghetti': 8, 'Bread': 7, 'Sushi': 7, 'spaghetti': 6, 'Cake': 6, 'Sandwich': 6, 'Blueberry': 6, 'pasta': 6, 'Salad.': 6, 'Blueberry pie': 5, 'Strawberry': 5, 'apple': 5, 'Blueberries': 5, 'Apple pie': 5, 'Lemon': 5, 'noodles': 5, 'blueberry cheesecake': 5, 'ramen': 5, 'sushi': 5, 'blueberry pie': 5, 'Coffee': 5, 'A salad': 5, 'Cheesecake': 5, 'Ice Cream': 4, 'Burger': 4, 'hot chocolate': 4, 'stale bread': 4, 'banana': 4, 'Chicken noodle soup': 4, 'cheese': 4, 'shawarma': 3, 'A salad.': 3, 'cheesecake': 3, 'Poutine': 3, 'apple pie': 3, 'tiramisu': 3, 'Oatmeal': 3, 'Matcha cake': 3, 'Pear': 3, 'Orange': 3, 'Porridge': 3, 'toast': 3, 'Chocolate': 3, 'Cold soup': 3, 'Rice': 3, 'Lasagna': 3, 'icecream': 3, 'octopus': 3, 'Watermelon': 3, 'Lettuce': 3, 'Caesar salad': 3, 'Pancake': 3, 'Banana': 3, 'Pizza.': 2, 'melted ice cream': 2, 'Apple': 2, 'strawberry': 2, 'Chicken': 2, 'mashed potatoes': 2, 'Icecream': 2, 'garden salad': 2, 'strawberries': 2, 'Fish': 2, 'Raspberry': 2, 'mooncake': 2, 'Taco': 2, 'blueberries': 2, 'burger': 2, 'A cake.': 2, 'Salmon': 2, 'steak': 2, 'Ramen': 2, 'caesar salad': 2, 'cereal': 2, 'matcha': 2, 'plum': 2, 'Cold noodles': 2, 'chicken noodle soup': 2, 'Melted cheese': 2, 'Chocolate Cake': 2, 'cupcake': 2, 'Pudding': 2, 'Cheeseburger': 2, 'Tea': 2, 'Loaf of bread': 2, 'fruit salad': 2, 'Vegetable Salad': 2, 'pancake': 2, 'Honey': 2, 'Mashed potatoes': 2, 'mint': 2, 'A dry sandwich': 2, 'kimchi': 2, 'Yogurt': 2, 'beef stew': 2, 'oatmeal': 2, 'Gruel': 2, 'Spaghetti.\xa0': 2, 'seaweed': 2, 'Stew': 2, 'Spaghetti\xa0': 2, 'croissant': 2, 'Burrito': 2, 'blueberry smoothie': 2, 'Eggs': 2, 'smoothie': 2, 'sandwich': 2, 'Blueberry muffin': 2, 'cotton candy': 2, 'Croissant': 2, 'Watermelon\xa0': 2, 'mac and cheese': 2, 'Dragonfruit': 2, 'Macaroni and cheese': 2, 'a salad': 2, 'apples': 2, 'Caviar': 2, 'Strawberry shortcake': 2, 'grape': 2, 'melted cheese': 2, 'noodle': 2, 'water': 2, 'Gummy candy': 1, 'ombre cake': 1, 'Cookie': 1, 'Noodles\xa0': 1, 'Something earthy like yam.\xa0': 1, 'Meat jelly': 1, "If this painting was a food, I guess it would be dark chocolate.\xa0 At first time looking at this painting it seems kind of bleak and unsettling.\xa0 The same way that dark chocolate isn't always the best tasting when you first try it.\xa0 However, the more you look at it, the more you acquire a calm appreciation for it, like how dark chocolate becomes enjoyable over time.\xa0": 1, 'Cottage cheese\xa0': 1, 'like an undercooked egg.\xa0': 1, 'cheese, maybe in a cheese board': 1, "Shepherd's Pie": 1, 'Popeyes\xa0': 1, 'Cold spaghetti.': 1, "A piece of speck that has been left outside of it's packaging for 2 days, making it more dry.": 1, 'A desert made of drinks like cocktail.': 1, 'beef wellington': 1, 'Crab.': 1, 'Fried rice': 1, 'a pizza': 1, 'Ginger': 1, 'Like a burnt soup.': 1, 'Iced American a little while ago': 1, 'wine.': 1, 'burnt toast': 1, 'A piece of pizza left out too long.': 1, 'A cold and tasteless soup': 1, 'carrot': 1, 'If this painting was a food, it would be something unpleasant and hard to swallow. I imagine it as a dish with a strange, almost rotten taste, where the flavours don’t match and make you feel uneasy as you eat it. The texture would be soft and limp in a way that feels wrong, and there might be a bitter or metallic aftertaste that lingers in your mouth. It is not comforting or satisfying at all – instead, it would be the kind of food that makes you lose your appetite and feel slightly disturbed, even after you stop eating.': 1, 'm&m cookies': 1, 'kiwi': 1, 'asparagus': 1, 'A homecooked meal like a stew.': 1, 'Day old bread': 1, 'Can of beans': 1, 'dark chocolate': 1, 'expired Jell-O': 1, 'Juice boxes': 1, 'Crackers with olive tapenade': 1, 'grilled cheese': 1, 'Pie crust': 1, 'French Onion with cheese': 1, 'soggy waffles': 1, 'lemon water': 1, 'It would be a dry whole-wheat sandwich.': 1, 'Pumpkin': 1, 'chocolate chip muffin.': 1, 'black coffee': 1, 'spaghetti?': 1, 'bad milk': 1, 'Pickles': 1, 'caramel': 1, 'It would be a slice of butter that has been left out in the hot sun for too long, starting to lose its shape and texture. Or maybe a very sticky caramel candy.': 1, 'smoked meat': 1, '无味明胶': 1, 'Sandwich. Loaf of bread.': 1, 'chocolate bar': 1, 'A melting ice cream sundae': 1, 'local cuisine, spicy bean dish': 1, 'Minced Beef': 1, 'Seaweed': 1, 'melted cheese and tomatoes that taste bad': 1, 'cold roasted chicken': 1, 'Hamburger with a mud patty inside.': 1, 'popcorn': 1, 'tomato': 1, 'sauteed greens': 1, 'bitter gourd': 1, 'poutine': 1, 'coffee bread': 1, 'bread, surface is hard inside is soft that kind of bread.': 1, 'Chestnuts': 1, 'multigrain bread': 1, 'Grilled cheese': 1, 'An orange': 1, 'Cereal': 1, 'Ice-cream': 1, 'any spoiled food': 1, 'A fudgy brownie': 1, 'hard boiled eggs': 1, 'Turkey sandwich': 1, 'Cheap cheese pizza': 1, 'Whisky': 1, "Shepard's Pie": 1, 'french onion soup': 1, 'Gyubee Japanese BBQ. Enjoyed the unlimited beef glitch (happiness) until the 2-hour limit is up (melting clocks, reality).': 1, 'Heavy stew.': 1, 'Cold fries :(': 1, 'Hard candy': 1, 'Chocolate.': 1, 'turkey sandwich': 1, 'It would be a pretzel.': 1, 'If this painitng was a food, I would describe it as cinnamon rolls.\xa0': 1, 'Butter\xa0': 1, 'A bowl of noodles': 1, 'stale pizza': 1, 'Pizza with pepperoni slices on it.': 1, 'White, unseasoned, rice that is cooked to perfection. You would have the rice with a japanese whisky so you can enjoy the after taste of the whisky and calm it down with the rice.': 1, 'Something warm and bright, like tomato soup': 1, 'It will be spaghetti. Especially the kind where the noodles are stiff, the meat sauce is not fresh, and it looks unappetizing.': 1, 'eggs': 1, 'it would be a spicy food, like tacos. Because some tacos can be really spicy and hot which makes me unhappy.\xa0': 1, 'Extremely old wine': 1, 'steamed dumplings': 1, 'slightly-melted ice cream': 1, 'Fruit bowl': 1, 'A cold bowl of ground beef and rice': 1, "Melted cheese on toast - something that's transformed from its original form into something droopy and soft, with warm golden colors that mirror the painting's palette.": 1, 'Meat stew': 1, 'Dried bread': 1, 'roasted duck': 1, 'alcohol': 1, 'white bread': 1, 'very plain noodles': 1, 'Onion soup': 1, "It would be something like my mother's cooking, like dumplings or baozi, something persistent throughout my life and hold fond memories for me, but also quite blurry given how many times I've consumed that food.": 1, 'Coq au Vin': 1, 'duck': 1, 'Bean salad': 1, 'Bread bun.': 1, 'whey': 1, 'Penne bolognese with a brandy manhatan': 1, 'Escargot': 1, 'Soup, in a cold day.': 1, 'A treat like chocolate or cupcakes.': 1, 'A bowl of ramen with a hearty broth.': 1, 'duck confit': 1, 'Tomato and scrambled eggs with rice': 1, 'Cold decaf coffee.': 1, 'Jolly Ranchers': 1, 'Pie': 1, 'Cake\xa0': 1, 'A bowl of black garlic miso ramen.': 1, 'Hot chocolate': 1, 'A cup of tea/coffee': 1, 'A hamburger': 1, 'Blueberry Pancakes': 1, 'Spicy noodles': 1, 'blueberry cake': 1, 'Atlantic Salmon': 1, 'It would be like a strong, rich soup.': 1, 'Hanamaki': 1, 'Pudding\xa0': 1, 'Soda.': 1, 'Blueberry and Miso Cheesecake': 1, 'Coffee with beautiful latte art': 1, 'ice cream sandwich': 1, 'cuttlefish ink spaghetti': 1, 'Curry': 1, 'cinnamon bun': 1, 'A dark chocolate ice cream.\xa0': 1, 'A high-end steak.': 1, 'Strawberry shortcake\n\n\xa0': 1, 'Creme brulee': 1, 'If this painting were a food, it would be hot honey. At first, it tastes familiar and sweet, but it quickly delivers an unexpected kick. This reflects how the painting initially feels calm, yet reveals a strong sense of chaos and emotional intensity the longer you look at it.': 1, 'Blueberry cheesecake\xa0': 1, 'Like a blue ice cream. Maybe some gelato or soft serve to emphasize the swirls.\xa0': 1, 'Dark Chocolate Truffle': 1, 'blueberry cheesecake swirly design': 1, 'Marshmallows.': 1, 'A sponge cake covered with subtle and not too sweet white frosting, topped with canned peaches, blue berries, kiwi, and a singular maraschino cherry.': 1, 'A warm bowl of potato soup.': 1, 'A cocktail': 1, 'rare steak\xa0': 1, 'Spring roll.': 1, 'A smoothie bowl.': 1, 'a cold soup': 1, 'Like a warm soup after a cold winter.': 1, 'donut\xa0': 1, 'a warm soup': 1, 'A blueberry pie with vanilla ice cream.': 1, 'If this painting was a food, it would be a sorbet with soft swirls of ice-blue and very pale lavender, served in a thin glass bowl. The flavours would be light and clean: a cool citrus note for the blue, and a faint floral taste for the purple, almost too gentle to name. It would not be very sweet—just enough to keep it from feeling harsh—so that what you remember most is the cold, clear freshness it leaves on your tongue. The surface would be smooth and slightly glossy, with soft swirls frozen into it, like gentle waves that have suddenly become still.\n\nThe drink would be clear and calm when you look at it, with the ice slowly melting and barely making a sound. It would be something you drink alone by a window, when the sky is dark and quiet, giving you a sense of peaceful distance. It would feel refreshing and clean, but also a little lonely, like a cold breeze that passes through a quiet town while everyone is asleep.': 1, "Snow white's poisoned apple\xa0": 1, 'wintermelon': 1, 'Burger, fries and beer': 1, 'Frozen pizza': 1, 'A cucumber': 1, 'Swiss Roll': 1, 'roast chicken': 1, 'Fresh pasta.': 1, 'ice cream cake': 1, 'Vanilla ice cream': 1, 'Hot Chocolate': 1, 'Frozen cheesecake': 1, 'It would be really good soft-serve icecream.': 1, 'Sparkling water': 1, 'overnight oats with blueberries': 1, 'an ice popsicle': 1, 'juice': 1, 'A strangely shaped cake': 1, 'Donut.': 1, 'fish and chips because of the town energy.': 1, 'chocolate pie': 1, 'A dark blueberry swirl cake with bright lemon zest on top. It tastes rich, cool, and slightly sharp.': 1, '黑咖啡': 1, 'Croissant. Oatmeal. Ice cream.': 1, 'blue pasta': 1, 'A bowl of spaghetti or ramen': 1, 'a condensed milk cake, like tres leches': 1, 'Cold Spaghetti': 1, 'boiled leafy greens': 1, 'polpo e fagioli': 1, 'Cake\n\n\xa0': 1, 'Squid ink pasta': 1, 'Cream Puff': 1, 'porridge': 1, 'It would be pizza': 1, 'Warm soup': 1, 'Bruschetta': 1, 'chocolate': 1, 'bagel': 1, 'A bug': 1, 'peppermint ice cream': 1, 'A big lollipop': 1, 'Apple pie.': 1, 'linguine pasta with zucchini': 1, 'Meringue': 1, 'Beef Wellington': 1, 'ice cream with sprinkles': 1, 'Mango smoothie': 1, 'Blueberries. The flows can be imagined as the explosion of the blueberries after one bite.': 1, 'A light soup.\xa0': 1, 'Cold milk tea': 1, 'pasta, specifically white sauce pasta': 1, 'Pudding Cake': 1, 'Pastry': 1, 'It would be warm milk with honey.': 1, 'Something like a fancier beef stew.': 1, 'If this painting was a food, I would describe it as a chocolate cake.': 1, 'eclair': 1, 'Cocktail\xa0': 1, 'blueberry yogourt': 1, 'Dark chocolate, bitter and darkly colored.': 1, 'durian': 1, 'Blueberry frozen yoghurt': 1, 'Filet mignon steak': 1, "Steak. The food isn't particularly brightly colored,visually striking, or eye-catching, but the taste is surprisingly delightful and enjoyable.": 1, 'Potato leek soup': 1, 'swirling blue berry smoothie bowl because it will just look liek the painting.\xa0': 1, 'Macaron': 1, 'spicy chicken': 1, 'It would be blueberry lemon cheesecake': 1, 'Clam chowder': 1, 'A warm bowl of dumpling soup.': 1, 'Blueberry pie with whipped cream and a dusting of golden sugar stars - rich, deep blue swirls with bright yellow accents, both comforting and magical.': 1, 'Blueberry vanilla cake': 1, 'starfruit': 1, 'Pepperoni pizza': 1, 'French onion soup': 1, 'hot soup that has a rich flavor, like the best Cream of Mushroom Soup.': 1, 'Omelette': 1, 'A night sandwich': 1, 'Cinnamon Bun': 1, 'Soda pop.': 1, 'a bowl of hot chicken noodle soup': 1, 'Clam chowder soup': 1, 'Milk and biscuits, something refreshi': 1, 'A refreshing drink, like cold water': 1, 'A vibrant set of cookies and biscuits.': 1, 'fruit platter': 1, 'Oven cooked mutton': 1, 'Christmas porridge': 1, 'Cake with ribbons': 1, 'Stir-fried lettuce with chili peppers': 1, 'An ice cream': 1, '\xa0a warm croissant\xa0': 1, 'an apple': 1, 'matcha tiramisu\xa0': 1, 'Seafood spaghetti.': 1, 'Garlic Bread': 1, 'A perfectly ripe pear': 1, 'Hot dog': 1, 'Vegetables.': 1, 'Grapes by the vine': 1, 'Strawberry shortcake.': 1, 'tea with biscuit': 1, 'The freshest and juiciest mango ever': 1, 'strawberry pie': 1, 'Cotton candy': 1, 'salad\xa0': 1, 'It would be pistachio gelato.': 1, 'Berries and cucumbers': 1, 'If this painting was a food it would be freshly baked cookies.\xa0 Like cookies, this painting is evokes calm, peaceful and positive feelings, the same way cookies do as a regular comfort food.\xa0\xa0': 1, 'Herbal tea\xa0': 1, 'some fruit, like a watermelon.\xa0': 1, 'Lotus Root Soup': 1, 'Wedding Cake': 1, 'Jasmine tea.': 1, 'A simple German strudel with powdered sugar and whipped cream, served with strawberries and blueberries.\xa0': 1, 'A salad with lettuce, tomatoes, and other greens.': 1, 'Fried Broccoli': 1, 'Caesar Salad': 1, 'a nice fresh salad paired with rose wine.': 1, 'Osmanthus sugar lotus root': 1, 'Poke.': 1, 'Vanilla and Strawberry ice cream': 1, 'a salad with great sauce': 1, 'Matcha Yuzu Mille-Feuille': 1, 'It will be a sandwich and snacks.': 1, 'oilseed rape': 1, 'matcha macaron\xa0': 1, 'A fresh spring salad with fruit and light dressing.': 1, 'A fruit cake': 1, 'cheesecake\xa0': 1, 'If this painting was a food, it would be a lightly sweet iced green tea or a cool jasmine drink served in a clear glass on a warm day. The taste would be gentle and clean, with a soft floral note and just a bit of natural sweetness. It would not be heavy at all, more like something you sip slowly while resting somewhere quiet. The drink would feel refreshing and soft at the same time, cool on the tongue but also comforting, with a calm, almost silent kind of loneliness that still feels peaceful.': 1, 'mochi matcha': 1, 'green apple\xa0': 1, 'sunflower seeds': 1, 'A french macaron.': 1, 'Homemade lasagna': 1, 'Mango sorbet': 1, 'A nice warm bowl of soup.': 1, 'This would be a fresh sandwich, made with fresh bread and vegetables.': 1, 'fruit cake\xa0': 1, 'Naan bread': 1, 'bright garden salad': 1, 'It would be a plate of cut fruits.\xa0': 1, 'Salmon with parsnip \xa0puree and watercress salad': 1, 'Spring mix salad': 1, "mom's homecooked meals": 1, 'Cool beverage': 1, 'Avocado.': 1, 'Greek salad': 1, 'peach, strawberries.': 1, 'matcha tea': 1, 'A fresh garden salad with light vinaigrette, or maybe a cup of herbal matcha tea. It tastes refreshing, organic, and light.': 1, 'acai bowl': 1, 'Clear soup Ramen': 1, 'Lettuce. Salad. Vegetables. Fruits.': 1, 'A caesar salad but without the croutons': 1, 'Fresh berries with honey': 1, 'jello': 1, 'Warm Soup': 1, 'green apple pie': 1, 'Sunny side up egg': 1, 'fine food': 1, 'Carbonara': 1, 'seaweed shortbread': 1, 'Orange juice.': 1, 'Assorted fruit': 1, 'It would be a salad with leafy greens and tomatoes': 1, 'Matcha latte with strawberry puree': 1, 'spinach.': 1, 'Tacos': 1, 'spaghetti and meatballs': 1, 'Smoothie': 1, 'Paint and Paper': 1, 'cucumber': 1, 'vegetable salad': 1, 'It would be tropical fruits of any kind.\xa0': 1, 'A fresh salad with light dressing.\xa0': 1, 'a fresh salad with fruits and arugula': 1, 'Cucumber.': 1, 'Sweet garden carrots': 1, 'Peeps': 1, 'fruit, vegetable and cheese platter': 1, 'Charcuterie board. A mandate for a picnic.': 1, 'Jelly': 1, 'It would be a light but decadent dessert, such as a sponge cake with a whipped cream-like icing and lemon.\xa0': 1, 'Gelato Mousse': 1, 'It would be a cream cheese bagel.': 1, 'Something with too many flavours.': 1, 'Salad\xa0': 1, 'Afternoon tea': 1, 'A flaky, floral pastry (eg. Yunnan rose flower cakes)': 1, 'Warm porridge or congee.': 1, 'Cake. Those cakes that look appealing make you want to eat them and bring you joy. It tastes good too, sweet and very flavorful.': 1, 'Chamomile tea': 1, 'It would be a matcha and white choclate cheese cake.\xa0': 1, 'Lotus cookie': 1, 'fish and chips': 1, 'It would be a fresh fruit tart with pistachio cream.': 1, 'Charcuterie board': 1, 'A pepperoni pizza.': 1, 'Fresh garden salad with edible flowers - light, refreshing, and full of natural greens with delicate pops of color, evoking the same sense of tranquility and connection to nature.': 1, 'Fruit custard / danish': 1, 'Peppermint water': 1, 'floral tea': 1, 'a refreshing salad': 1, 'mineral water': 1, 'Vanilla ice cream with light cream, less sugar, and a bit of freshness.': 1, 'Spinach with rice': 1, "It reminds me of salad and lettuce. Just a calm, easy and green staple food, that doesn't do too much, and acts as a great comfort food at times.": 1, 'A fruit bowl.': 1, 'a muffin': 1, 'Matcha cake.': 1, 'Flower': 1, 'a yogurt bowl with cereal, fruits and honey': 1, 'Eggs benedict with a glass of orange juice': 1, 'Lava cake': 1, 'Mushroom cream soup': 1, 'bowl of lentil soup': 1, 'very dull baked beans\xa0': 1, 'Muffin': 1, 'A hot bowl of soup': 1, 'a cold sandwich, once delicious': 1, 'Worms': 1, 'Plain rice': 1, 'Expired bread': 1, 'Chicken breast': 1, 'Melting ice cream': 1, 'Brown rice': 1, 'Casserole': 1, 'chowder': 1, 'Stuffed turkey': 1, 'chocolate chip cookie': 1, 'Noodles': 1, 'Pecan pie.': 1, 'Molten chocolate cake': 1, 'lobster': 1, 'Sharawma\xa0': 1, 'Congee': 1, 'a dish that would give me nostalgia like a dish that my mother made when i was a kid': 1, 'rice, frequent but influential.\xa0': 1, 'Plain Toast': 1, 'cheese pizza': 1, 'A gooey caramel sundae with melting ice cream and rich flavors, sweet and surreal.': 1, 'Grapefruit\xa0': 1, 'Crispy french fries': 1, 'French Fry': 1, 'Cheese fondue\xa0': 1, 'Lukewarm Soup': 1, 'Soup.': 1, 'broccoli': 1, 'Bread with jam. I chose this because the items in the painting were relatively contrasting in color from the desert/background.': 1, 'fruits': 1, 'Tiramisu': 1, 'Fries': 1, 'popsicle': 1, 'Pizza because of the colours': 1, 'mcdonalds': 1, 'butter': 1, 'French fries': 1, 'Sardines': 1, 'An overripe peach': 1, 'Turkey': 1, 'Apple Pie': 1, 'Some sort of soft jelly.': 1, 'It would be like add fish in oatmeal. The fish is mildly gross, and put in the boring, benal oatmeal somehow makes both things worse off. It makes me question why it exists, like I would that meal.': 1, 'Corn': 1, 'Warm brownie': 1, 'orange': 1, 'Plain bread': 1, 'Cheese fondue': 1, 'Boiled beans': 1, 'Popscicle\xa0': 1, 'adjarian khachapuri': 1, 'Popeyes biscuit with no bev': 1, 'Banana\xa0': 1, 'It would be a mushy piece of bread.': 1, 'porage': 1, 'Stale bread because this painting is depressing and hard to understand, just like how stale bread is unfortunate and hard to chew on.': 1, 'Stale potato chips.\xa0': 1, 'Chocolate left out in the sun.': 1, 'Untoasted bread with turkey slices': 1, 'A mushroom soup': 1, 'pie': 1, 'bread. Definitely something with a less prominent, neutral taste with a dry texture.': 1, 'A bad meal - so maybe something like, broccoli.\xa0': 1, 'A dessert that looks soft and melting, like something left out too long, sweet but slightly uncomfortable to consume.': 1, 'curry': 1, 'A kiwi': 1, 'cantelope': 1, 'Nachos and salsa.\xa0': 1, 'Chili': 1, 'melted ice-cream': 1, 'Spicy Curry': 1, 'Bread.\xa0': 1, 'Overripe fruit': 1, 'Burnt pizza': 1, 'Sausage\xa0': 1, 'Barely stale bread': 1, 'Something harsh like a rotten orange': 1, 'cold rice and chicken': 1, 'Butterscotch Icecream.': 1, 'A big burger': 1, 'Panna cotta': 1, 'It would be a hamburger.': 1, 'A fish like salmon, or a lobster.': 1, 'plain white rice': 1, 'Pumpkin pie': 1, 'Thanksgiving dinner': 1, 'Churros.': 1, 'Raclette': 1, 'Caramel Puddin

We can see that there are a lot of duplicates that did not get paired together. Theres a "Salad" and "salad" value, being treated
separately, we want those paired together.

In [334]:
# This will group values like "Ice cream" and "ice cream together", "Pizza" and "a pizza".
data["Q13"] = (
    data["Q13"]
    .str.lower()
    .str.strip()
    .str.replace(r'[^a-z\s]', '', regex=True)   # remove punctuation
    .str.replace(r'\b(a|an|the)\b', '', regex=True)  # remove articles
    .str.replace(r'\s+', ' ', regex=True)  # clean extra spaces
)

We will have to manually group some values as well, below we replace certain texts to match out value entries, so that they can get paired together.

In [335]:
def normalize(text):
    text = str(text).lower().strip()
    
    # General fixes
    text = text.replace("apples", "apple")
    text = text.replace("noodles", "noodle")
    text = text.replace("ramen", "noodle")
    text = text.replace("eggs", "egg")
    text = text.replace("pancakes", "pancake")
    text = text.replace("grapes", "grape")
    text = text.replace("beans", "bean")
    text = text.replace("lentils", "lentil")
    text = text.replace("hotdog", "hot dog")
    text = text.replace("hot dogs", "hot dog")
    text = text.replace("fruits", "fruit")
    text = text.replace("tacos", "taco")
    text = text.replace("brownies", "brownie")
    text = text.replace("cookies", "cookie")
    text = text.replace("vegetables", "vegetable")

    # common variants
    text = text.replace("blue berry", "blueberry")
    text = text.replace("blueberries", "blueberry")
    text = text.replace("blackberries", "blackberry")
    text = text.replace("raspberries", "raspberry")
    text = text.replace("strawberries", "strawberry")
    text = text.replace("hamburger", "burger")
    text = text.replace("cheeseburger", "burger")
    text = text.replace("cheesecake", "cake")
    text = text.replace("cupcake", "cake")
    text = text.replace("cosmic brownies", "cake")
    text = text.replace("macaron", "cake")
    text = text.replace("cream puff", "cake")
    text = text.replace("brownie", "cake")
    text = text.replace("flan", "cake")
    text = text.replace("panna cotta", "cake")
    text = text.replace("creme brulee", "cake")
    text = text.replace("swiss roll", "cake")
    text = text.replace("croquembouche", "cake") 
    text = text.replace("tiramisu", "cake") 
    text = text.replace("parfait", "cake")  
    text = text.replace("meringue", "cake") 
    text = text.replace("oreo", "cookie")
    text = text.replace("omelette", "egg")
    text = text.replace("jolly ranchers", "candy")
    text = text.replace("lollipop", "candy")
    text = text.replace("carrot", "vegetable")
    text = text.replace("asparagus", "vegetable")
    text = text.replace("cabbage", "vegetable")
    text = text.replace("green peas", "vegetable")
    text = text.replace("boiled leafy greens", "vegetable")
    text = text.replace("sauteed greens", "vegetable")
    text = text.replace("waffles", "pancake")
    text = text.replace("bagel", "bread")
    text = text.replace("bruschetta", "bread")
    text = text.replace("alcohol", "wine") 
    text = text.replace("whisky", "wine")
    text = text.replace("kool aid", "juice")
    text = text.replace("lemonade", "juice")
    text = text.replace("olives", "fruit")
    text = text.replace("costco hot dog", "hot dog")

    # fries handling (important)
    text = text.replace("french fries", "fry")
    text = text.replace("fries", "fry")

    # desserts / dairy variants
    text = text.replace("icecream", "ice cream")
    text = text.replace("gelato", "ice cream")
    text = text.replace("sorbet", "ice cream")
    text = text.replace("yogurt", "yogurt")
    text = text.replace("popsicle", "ice cream")
    text = text.replace("sundae", "ice cream")
    text = text.replace("frozen yoghurt", "yogurt")

    # drinks
    text = text.replace("latte", "coffee")
    text = text.replace("iced coffee", "coffee")

    # spelling mistakes
    text = text.replace("spagetti", "spaghetti")
    text = text.replace("sandwhich", "sandwich")
    text = text.replace("doughnut", "donut")
    text = text.replace("popscicle", "popsicle")
    text = text.replace("bluberries", "blueberry")
    text = text.replace("macha", "matcha")

    return text

Now we will make a list of all the unique foods we saw in the responses, and go through each response and see if it contains a word we see in our list. For eg: "This painting reminds me of pizza", should be paired with "pizza".

In [336]:
# Now we will go through all the responses, and see if they contain a word that is present in our more popular responses:
top_foods = ['apple', 'asparagus','avocado','banana','bean','beef','bread','broccoli','burger', 'butter', 'blueberry', 'blackberry', 
            'candy', 'cake','caramel','carrot','caviar','cereal','cheese','chicken','chocolate', 'coffee','cookie','corn','crab','croissant','cucumber','cupcake','curry',
            'donut','duck','durian',
            'egg',
            'fish','flan','fry','fruit',
            'garlic','ginger','goose','grape','grapefruit','guacamole',
            'ham','honey','hummus',
            'ice cream', 
            'jelly','juice',
            'kimchi','kiwi',
            'lamb','lasagna','lemon','lentil','lettuce', 'lobster',
            'mango','meat', 'matcha','milk','mint','mochi','muffin','mushroom',
            'naan','noodle',
            'oatmeal','octopus','olive','omelette','onion','orange',
            'pancake', 'pasta','pastry','peach','pear','pepper','pickle','pie','pizza','plum', 'popcorn','pork','potato','poutine','pretzel','pudding','pumpkin', 
            'raspberry', 'rice',
            'salad','salmon','sandwich','sausage','seaweed','shrimp','smoothie', 'soda','soup','spaghetti','spinach','squid','steak','strawberry','sugar', 'sushi',
            'tea', 'taco', 'toast','tomato','tuna','turkey',
            'vegetable',
            'water','watermelon', 'wine',
            'yogurt'
]

top_foods = sorted(top_foods, key=len, reverse=True)

import re

def map_food(text):
    text = normalize(text)
    
    for food in top_foods:
        if re.search(r'\b' + re.escape(food) + r'\b', text):
            return food
    
    return text

data["Q13"] = data["Q13"].apply(map_food)

In [337]:
food_counts = data["Q13"].value_counts().to_dict()
print(food_counts)

{'salad': 136, 'ice cream': 99, 'blueberry': 87, 'cake': 72, 'pizza': 54, 'soup': 54, 'bread': 52, 'cheese': 48, 'chocolate': 43, 'sandwich': 36, 'noodle': 34, 'spaghetti': 33, 'apple': 32, 'strawberry': 29, 'pasta': 27, 'fruit': 25, 'chicken': 22, 'steak': 18, 'burger': 17, 'matcha': 17, 'vegetable': 16, 'tea': 15, 'watermelon': 14, 'coffee': 14, 'rice': 13, 'egg': 12, 'sushi': 12, 'beef': 12, 'pie': 11, 'water': 10, 'candy': 9, 'lettuce': 9, 'cookie': 9, 'banana': 9, 'toast': 9, 'smoothie': 8, 'grape': 8, 'salmon': 8, 'orange': 8, 'pancake': 8, 'lemon': 8, 'bean': 7, 'potato': 7, 'fry': 7, 'croissant': 7, 'lasagna': 7, 'pudding': 6, 'wine': 6, 'taco': 6, 'cereal': 6, 'juice': 6, 'fish': 6, 'broccoli': 6, 'cucumber': 6, 'honey': 6, 'hot dog': 6, 'oatmeal': 6, 'mashed potatoes': 5, 'tomato': 5, 'turkey': 5, 'spinach': 5, 'seaweed': 5, 'milk': 5, 'duck': 4, 'porridge': 4, 'butter': 4, 'raspberry': 4, 'poutine': 4, 'pear': 4, 'lentil': 3, 'caramel': 3, 'mango': 3, 'jelly': 3, 'lobster': 3, 'bitter melon': 3, 'shawarma': 3, 'octopus': 3, 'onion': 3, 'donut': 3, 'pastry': 3, 'curry': 3, 'pumpkin': 3, 'meat': 3, 'mooncake': 3, 'mushroom': 3, 'yogurt': 3, 'gruel': 2, 'peach': 2, 'muffin': 2, 'corn': 2, 'kiwi': 2, 'mochi': 2, 'cinnamon roll': 2, 'burrito': 2, 'smores': 2, 'shrimp': 2, 'stew': 2, 'lamb': 2, 'kimchi': 2, '': 2, 'eclair': 2, 'soda': 2, 'plum': 2, 'popcorn': 2, 'garlic': 2, 'cinnamon bun': 2, 'jello': 2, 'avocado': 2, 'acai bowl': 2, 'mint': 2, 'sugar': 2, 'dragonfruit': 2, 'caviar': 2, 'cocktail': 2, 'spring roll': 2, 'ratatouille': 1, 'sandwiches': 1, 'green onions': 1, 'guacamole': 1, 'chipotle bowl': 1, 'hot pot': 1, 'vegetarian foods': 1, 'appetizer': 1, 'sugarcane': 1, 'cherry': 1, 'melons': 1, 'human toenail': 1, 'fresh spring rolls': 1, 'hot cocoa': 1, 'raw veggies': 1, 'vegan pcoffeer': 1, 'coconut': 1, 'wintermelon': 1, 'marshmallows': 1, 'christmas porridge': 1, 'oven cooked mutton': 1, 'starfruit': 1, 'clam chowder': 1, 'durian': 1, 'bug': 1, 'bitter gourd': 1, 'hanamaki': 1, 'cup of teacoffee': 1, 'escargot': 1, 'penne bolognese with brandy manhatan': 1, 'whey': 1, 'coq au vin': 1, 'it would be something like my mothers cooking like dumplings or baozi something persistent throughout my life and hold fond memories for me but also quite blurry given how many times ive consumed that food': 1, 'polpo e fagioli': 1, 'cool beverage': 1, 'moms homecooked meals': 1, 'sunflower seeds': 1, 'oilseed rape': 1, 'poke': 1, 'berries and cucumbers': 1, 'homecooked meal like stew': 1, 'steamed dumplings': 1, 'if this painitng was food i would describe it as cinnamon rolls': 1, 'pretzel': 1, 'heavy stew': 1, 'any spoiled food': 1, 'chestnuts': 1, 'pickles': 1, 'olive': 1, 'expired jello': 1, 'chowder': 1, 'casserole': 1, 'worms': 1, 'flower': 1, 'charcuterie board': 1, 'warm porridge or congee': 1, 'something with too many flavours': 1, 'charcuterie board mandate for picnic': 1, 'peeps': 1, 'sweet garden vegetables': 1, 'paint and paper': 1, 'carbonara': 1, 'fine food': 1, 'sausage': 1, 'chili': 1, 'nachos and salsa': 1, 'cantelope': 1, 'dessert that looks soft and melting like something left out too long sweet but slightly uncomfortable to consume': 1, 'porage': 1, 'popeyes biscuit with no bev': 1, 'adjarian khachapuri': 1, 'popsicle': 1, 'mcdonalds': 1, 'grapefruit': 1, 'dish that would give me nostalgia like dish that my mother made when i was kid': 1, 'congee': 1, 'sharawma': 1, 'soft halfmelted custard left out too long served cold on warm plate': 1, 'nigerian food': 1, 'biscuits': 1, 'it would be meatloaf': 1, 'nutrient slop bar with no taste': 1, 'foie gras': 1, 'moms home cooking': 1, 'some amalgamation of random food combinations that end up working together': 1, 'goulash': 1, 'tuna': 1, 'french snail': 1, 'pickle': 1, 'raclette': 1, 'if this painting was food it would be something unpleasant and hard to swallow i imagine it as dish with strange almost rotten taste where flavours dont match and make you feel uneasy as you eat it texture would be soft and limp in way that feels wrong and there might be bitter or metallic aftertaste that lingers in your mouth it is not comforting or satisfying at all instead it would be kind of food that makes you lose your appetite and feel slightly disturbed even after you stop eating': 1, 'iced american little while ago': 1, 'ginger': 1, 'crab': 1, 'desert made of drinks like cocktail': 1, 'piece of speck that has been left outside of its packaging for days making it more dry': 1, 'thanksgiving dinner': 1, 'burnt marshmallow': 1, 'borscht': 1, 'cold dessert slowly melting in desert': 1, 'pears': 1, 'crackers': 1, 'fallen leaf': 1, 'sleepingpill infused gummy bear': 1, 'plate of untouched cold cakei': 1, 'i would say something very mellow like cucumbers as it doesnt taste like much to someone who doesnt like it but it is enjoyable to those who do like it': 1, 'childhood favorite that is not as good as you remembered it': 1, 'canned herring': 1, 'raisin': 1, 'hummus': 1, 'pomegranates': 1, 'buegwe': 1, 'comforting warm meal on cold night but with strong flavours that would stay with you for long': 1, 'pomegranate': 1, 'tilapia': 1, 'freezie': 1, 'creme brule': 1, 'skewers from street food vendor': 1, 'dessert': 1, 'prime rib': 1, 'human foot': 1, 'goose': 1, 'slop food everything mixed together so you cant tell what food even is': 1, 'ice cube': 1, 'this painting would be butternut squash': 1, 'naturally occurring carbon black vitis sourced exclusively from sicily': 1, 'bouquet of candies and chocolates': 1, 'filet mignon': 1, 'blackberry': 1, 'mocktail': 1, 'astronaut food tubes': 1, 'it would be like rich intensely spiced stew deep dark flavors layered with sudden bursts of brightness': 1, 'pesto fettucine': 1, 'ice': 1, 'slightly burnt marshmallow bit sad bit tainted but still tastes really good': 1, 'beavertail': 1, 'fettuccine': 1, 'cold beer': 1, 'pineapple this painting would be sweet and sour it would taste good but not amazing': 1, 'popeyes': 1, 'something earthy like yam': 1, 'deconstructed big mac at high end restaurant': 1, 'i cant imagine it as food': 1, 'taro boba': 1, 'it would be any happy comforting food': 1, 'grass': 1, 'this painting would be granola bar': 1, 'marmalade': 1, 'snow cone': 1, 'it would be light and refreshing dish with subtle flavors calming and easy to enjoy': 1, 'wheatgrass protein shake': 1, 'this would be desert like custard': 1, 'sweets and desserts': 1, 'berries': 1, 'cherries': 1, 'cornucopia': 1, 'lotus root': 1, 'it would be congee': 1, 'churros': 1, 'sardines': 1}

We now have paired as many entries together as we can, we can now figure out how many categories this question should have. We have decided that any food with 10 or more entries (for now), will be included as a category. We can drop entries with categories less than this amount:

In [338]:
x = 5  

# count how many times each food appears
counts = data["Q13"].value_counts()

# keep only rows where Q13 appears at least x times
data = data[data["Q13"].map(counts) >= x]

In [341]:
# Create indicator features
foods = data["Q13"].value_counts().index

for food in foods:
    col_name = food.replace(" ", "_")  # ice cream → ice_cream
    data[f"food_{col_name}"] = (data["Q13"] == food).astype(int)

In [339]:
data["Q13"].value_counts()

Q13
salad              136
ice cream           99
blueberry           87
cake                72
pizza               54
                  ...
turkey               5
mashed potatoes      5
seaweed              5
milk                 5
spinach              5
Name: count, Length: 63, dtype: int64

We can now make indicator features off these categories:

**Making the Output Numeric**

We have three paintings that a new input can be classified as: "The Persistence of Memory", "The Water Lily Pond", "The Starry Night". We can map these as 1,2,3:

In [197]:
# Create new mappings
painting_mapping = {"The Persistence of Memory": 1, "The Water Lily Pond": 2, "The Starry Night": 3}

# Map paintings to numerical values.
data["Painting"] = data["Painting"].map(painting_mapping)

In [342]:
data.head()

,unique_id,Painting,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,...,food_taco,food_cereal,food_broccoli,food_honey,food_tomato,food_turkey,food_mashed_potatoes,food_seaweed,food_milk,food_spinach
1,2,The Persistence of Memory,5.0,"The clocks are burnt on a hot desert, it embod...",4.0,3.0,2.0,1.0,2.0,4.0,...,0,0,0,0,0,0,0,0,0,0
5,6,The Persistence of Memory,7.0,This painting makes me feel a bit confused and...,4.0,2.0,1.0,5.0,5.0,6.0,...,0,0,0,0,0,0,0,0,0,0
6,7,The Persistence of Memory,8.0,It has a sorrow feeling and clock is melting f...,4.0,2.0,2.0,4.0,3.0,3.0,...,0,0,0,0,0,0,0,0,0,0
7,8,The Persistence of Memory,4.0,"The painting makes me feel somewhat sad, think...",4.0,2.0,2.0,4.0,7.0,8.0,...,0,0,0,0,0,0,0,0,0,0
8,9,The Persistence of Memory,8.0,"eerie, moody, confused",5.0,2.0,2.0,4.0,3.0,4.0,...,0,0,0,0,0,0,0,0,0,0

In [199]:
data.tail()

,unique_id,Painting,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,...,10e,11a,11b,11c,11d,11e,12a,12b,12c,12d
1681,558,2,5.0,Joy and relaxation.,2.0,4.0,4.0,2.0,2.0,1.0,...,1,1,1,1,1,1,1,0,0,0
1682,559,2,9.0,This painting makes me feel happy,2.0,5.0,5.0,1.0,3.0,3.0,...,0,1,0,0,0,0,1,1,0,0
1683,560,2,8.0,This painting makes me feel warm and new birth...,1.0,5.0,3.0,1.0,2.0,2.0,...,0,1,1,0,0,0,1,0,0,0
1684,561,2,5.0,makes me feel nonchalant,2.0,2.0,4.0,1.0,4.0,1.0,...,0,1,1,1,1,1,1,0,0,0
1685,562,2,4.0,Makes me feel very calm and relaxed as it give...,1.0,5.0,5.0,1.0,4.0,4.0,...,1,1,1,0,0,1,1,1,0,0

In [340]:
data.shape

(1288, 27)

In [343]:
print(f'Number of columns: {len(data.columns)}')
for column_name in data.columns:
    print(column_name)

Number of columns: 90
unique_id
Painting
Q1
Q2
Q3
Q4
Q5
Q6
Q7
Q8
Q9
Q13
Q14
10a
10b
10c
10d
10e
11a
11b
11c
11d
11e
12a
12b
12c
12d
food_salad
food_ice_cream
food_blueberry
food_cake
food_pizza
food_soup
food_bread
food_cheese
food_chocolate
food_sandwich
food_noodle
food_spaghetti
food_apple
food_strawberry
food_pasta
food_fruit
food_chicken
food_steak
food_burger
food_matcha
food_vegetable
food_tea
food_watermelon
food_coffee
food_rice
food_beef
food_egg
food_sushi
food_pie
food_water
food_toast
food_candy
food_lettuce
food_banana
food_cookie
food_grape
food_smoothie
food_orange
food_lemon
food_salmon
food_pancake
food_potato
food_croissant
food_fry
food_bean
food_lasagna
food_fish
food_cucumber
food_hot_dog
food_pudding
food_wine
food_oatmeal
food_juice
food_taco
food_cereal
food_broccoli
food_honey
food_tomato
food_turkey
food_mashed_potatoes
food_seaweed
food_milk
food_spinach